---
- name: Fail for invalid selections of roles.
  ansible.builtin.fail:
    msg: |
      Invalid value {{ condor_role }} for condor_role. Either choose one of
      "execute", "submit" or "central-manager"; or choose "all" for a
      single-machine installation.
  when: condor_role not in ('all', 'submit', 'execute', 'central-manager')

- name: Check if central manager role is present.
  ansible.builtin.command: grep -nr "use role:get_htcondor_central_manager" /etc/condor/config.d
  register: manager
  changed_when: false
  failed_when: manager.rc not in (0, 1, 2)
  ignore_errors: true

- name: Print central manager role installed.
  ansible.builtin.debug:
    msg: "Central manager role installed."
  when: manager.stdout | length > 0

- name: Print central manager role not installed.
  ansible.builtin.debug:
    msg: "Central manager role not installed."
  when: manager.rc in (1, 2)

- name: Check if submit role is present.
  ansible.builtin.command: grep -nr "use role:get_htcondor_submit" /etc/condor/config.d
  register: submit
  changed_when: false
  failed_when: submit.rc not in (0, 1, 2)

- name: Print submit role installed.
  ansible.builtin.debug:
    msg: "Submit role installed."
  when: submit.stdout | length > 0

- name: Print submit role not installed.
  ansible.builtin.debug:
    msg: "Submit role not installed."
  when: submit.rc in (1, 2)

- name: Check if execute role is present.
  ansible.builtin.command: grep -nr "use role:get_htcondor_execute" /etc/condor/config.d
  register: execute
  changed_when: false
  failed_when: execute.rc not in (0, 1, 2)

- name: Print execute role installed.
  ansible.builtin.debug:
    msg: "Execute role installed."
  when: execute.stdout | length > 0

- name: Print execute role not installed.
  ansible.builtin.debug:
    msg: "Execute role not installed."
  when: execute.rc in (1, 2)
