---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rockylinux-8
    image: rockylinux:8
    pre_build_image: false
    systemd: true
    privileged: true
    command: "/usr/sbin/init"
    tty: true
    dockerfile: ../Dockerfile.j2
  - name: rockylinux-9
    image: rockylinux:9
    pre_build_image: false
    systemd: true
    privileged: true
    command: "/usr/sbin/init"
    tty: true
    dockerfile: ../Dockerfile.j2
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
